### ISSUE TITLE
Bool instances

### ISSUE THREAD

**Issue by fizruk** [fizruk/http-api-data#4]
`Servant.Common.Text` defines `ToText`/`FromText` instance for `Bool` to use lowercase `Text` representation:

```
>>> fromText ("true"::Text) :: Maybe Bool
Just True
>>> fromText ("false"::Text) :: Maybe Bool
Just False
```

`path-pieces` reuses `Show`/`Read` instances for `Bool`.

Which one should we use?

P. S. I personally like `path-pieces` version because it does not make `Bool` special.

**Comment by fizruk** [comment]
@jkarni I guess I'm just waiting for your approval here.

**Comment by jkarni** [comment]
My own opinion is that both capitalized and uncapitalized should decode. (Certainly the expected behaviour for query params is that e.g. `true` should work.) As for special-casing, as I see it `Show`/`Read` don't have much to do with `To/FromText` - they just happen to coincide for a lot of base datatypes.

**Comment by gregwebs** [comment]
If they both decode the question is then: what happens when encoding? Although I tend to favor Haskell defaults I can see why one would not want to bother with capitalizing and uncapitalizing. There might be a case to be made for being the same (or different) as Javascript: one can do `true.toString()` to get the uncapitalized verson.

**Comment by fizruk** [comment]
Okay, I think I am going to make encoding in lower case and decoding case-insensitive.

With `Maybe a` instance and idea of Generic-based deriving (discussed in #3) the same approach should be taken as with `Bool` to make things uniform. E. g. `Just "HELLO"` should be encoded with constructor tag name lower cased for encoding (`just HELLO`) and decoded with tag name in any case (e.g. `Just HELLO`, `JUST HELLO`, etc.).
