### ISSUE TITLE
Deprecate PathPiece?

### ISSUE THREAD

**Issue by fizruk** [fizruk/http-api-data#5]

**Comment by gregwebs** [comment]
I think the best course of action is to keep the path-pieces package but release a new version with the changes to the TypeClass that you made here. Otherwise we are in the position of 2 packages defining the same typeclass. After that release we can switch packages that depend on path-pieces package over to http-api-data and then finally deprecate path-pieces. Does that make sense?

**Comment by fizruk** [comment]
Yes, this totally makes sense!

**Comment by fizruk** [comment]
I order to deprecate `path-pieces` package we need to deal with `PathMultiPiece`.

It seems that `PathMultiPiece` is only used for `[a]`.
If this is true, we can simply eliminate the class and provide corresponding functions:

```haskell
toUrlPieces :: ToHttpApiData a => [a] -> [Text]
toUrlPieces = fmap toUrlPiece

parseUrlPieces :: FromHttpApiData a => [Text] -> Either Text [a]
parseUrlPieces = traverse parseUrlPiece
```

**Comment by gregwebs** [comment]
I suspect the idea of PathMultiPiece is that it allowed flexibility for user definitions, but I have never used this feature (and it is rarely used in general). @snoyberg might be able to provide more insight.

**Comment by snoyberg** [comment]
That's probably a reasonable simplification

**Comment by fizruk** [comment]
Closing this since yesodweb/path-pieces#13 exists.
Feel free to reopen if you have anything to add :)
