### ISSUE TITLE
Support for Cabal 2.2?

### ISSUE THREAD

**Issue by snoyberg** [fizruk/http-api-data#72]
The current version of http-api-data on Hackage has an upper bound in its `custom-setup` stanza preventing Cabal 2.2. Would it be possible to relax that, either via a new release or a revision?

**Comment by phadej** [comment]
See #71

**Comment by snoyberg** [comment]
Why would you block usage of this package with older versions of GHC and newer versions of Cabal? That's exactly the use case I have right now, and a relaxed upper bound would solve that for me immediately, without need to wait for blaze-builder.

**Comment by phadej** [comment]
@snoyberg Solving for you immediately means more work for me now. I'm very sorry, but I (and other people) have to prioritize tasks. I'd already made a release if not the blocker.

Please use `--allow-newer` until then, it's a feature specifically for such situations. (Unfortunately `blaze-builder` requires code level changes).

For the record: `cabal new-build` can use `Cabal-2.0` for `setup-depends` even the main plan requires `Cabal-2.2`, so this issue is solved with a proper tooling:

```
http-api-data master % git diff
diff --git a/http-api-data.cabal b/http-api-data.cabal
index d661e05..b051a46 100644
--- a/http-api-data.cabal
+++ b/http-api-data.cabal
@@ -41,6 +41,7 @@ library
     hs-source-dirs: src/
     include-dirs:   include/
     build-depends:   base                  >= 4.7      && < 4.11
+                   , Cabal >= 2.2
                    , attoparsec            >= 0.13.0.1 && < 0.14
                    , attoparsec-iso8601    >= 1.0.0.0  && < 1.1
                    , bytestring            >= 0.10.4.0 && < 0.11

http-api-data master % cabal new-build --dry
Build profile: -w ghc-8.2.2 -O1
In order, the following would be built (use -v for more details):
 - Cabal-2.2.0.0 (lib) (requires build)
 - http-api-data-0.3.7.2 (lib:http-api-data) (cannot read state cache)
```

**Comment by snoyberg** [comment]
Sure, proper tooling is completely capable of ignoring the erroneous version bounds just fine. The only reason for the concern here is people who are trying to run `cabal install stack` from Hackage. Which is increasingly looking like a concern we won't be able to address.

**Comment by phadej** [comment]
As I implied in previous comment, `cabal new-install stack` would work just fine (on GHC-8.2).

**Comment by hvr** [comment]
Fwiw, if the intent is to be able to install http-api-data w/ GHC 8.4.1, there's no `cabal-install-2.2` released yet anyway, which is a declared requirement for GHC 8.4.1. So I don't think there's urgency to address this, since as pointed out, there is perfectly valid install-plans for GHC 8.2.1 which don't require Cabal-2.2.

**Comment by fizruk** [comment]
@snoyberg I've just released a [`http-api-data-0.3.8`](http://hackage.haskell.org/package/http-api-data-0.3.8) with the requested change (and a couple others). I hope this will work out for you!

If I understood correctly the problem here was mainly that the requested change was of low priority to @phadej and he just had (and still has) a lot on his plate already. As you can see I also couldn't address the issue right away and only got to it 2 days later.

Apparently there is no disagreement about the change itself, only its priority. If that's really the case I guess I could simply add @snoyberg as a co-maintainer of this package so he could make such changes in the future with ease. I think we could all benefit from having more co-maintainers (especially ones like @snoyberg)!

What do you think?

**Comment by snoyberg** [comment]
Thanks! I'm moving Stack over to using this new release so that the next release will be buildable from Hackage.

Thank you for the offer. I'm definitely on board with comaintainer status. I doubt I'll have any input on the library itself, but between Stack and Stackage maintenance I can pitch in with version bounds issues.

**Comment by fizruk** [comment]
> Thank you for the offer. I'm definitely on board with comaintainer status.

@snoyberg I have now sent you an invite to this repo and added you as a co-maintainer on Hackage! Welcome!

**Comment by snoyberg** [comment]
Thanks!

On Tue, Mar 13, 2018 at 11:20 AM, Nickolay Kudasov <notifications@github.com
